Repository Financial-Times/o-autocomplete, pull requests merged in 2021-07, with the labels that each got.

#5 update to the latest major version of @testing-library/dom
  package-lock.json
  package.json
  test/js/autocomplete.test.js
  test/js/helpers/hack.js
Labels: component

#6 use origami-percy v2 which works with npm only components
  .github/workflows/percy.yml
Labels: component

#7 Correct static demo html
  demos/src/static/static.mustache
Labels: component, release:patch

#8 Update support status
  origami.json
Labels: component, release:patch

#9 Update demo titles
  origami.json
Labels: component, release:patch

#11 Only allow specific options to be passed to accessible-autocomplete
  src/js/autocomplete.js
  test/js/autocomplete.test.js
Labels: bug, component, release:patch

#13 Add an onConfirm function which is called when the user selects an option
  README.md
  demos/src/dynamic-complex/dynamic-complex.js
  demos/src/dynamic-complex/dynamic-complex.mustache
  src/js/autocomplete.js
  test/js/autocomplete.test.js
Labels: component, release:minor

#14 Preserve source elements' attributes
  package-lock.json
  src/js/autocomplete.js
  test/js/autocomplete.test.js
  test/js/helpers/fixtures.js
Labels: component, feature, release:minor
